#!/usr/bin/env bash
set -e

# make the cwd of this script, the actual directory location of it
# otherwise it could be the cwd of the user, or node_modules/bin
# requires coreutils on mac: brew install coreutils
# https://stackoverflow.com/q/3349105/130638
function rlink {
	if test -n "$(which realpath)"; then
		realpath "$0"
	elif test -n "$(which greadlink)"; then
		greadlink -f "$0"
	elif test -n "$(which readlink)"; then
		readlink -f "$0"
	else
		echo "missing either: realpath, greadlink, readlink"
		exit 1
	fi
}
path="$(dirname "$(rlink "$0")")"

# determine platform and its executable
if test "$(uname -s)" = "Linux"; then
	bin="stout-linux"
elif test "$(uname -s)" = "Darwin"; then
	bin="stout-osx"
else
	bin="stout-windows.exe"
fi

# determine if we have env vars defined
# if so, run the executable with the env vars
# if not, run it normally
if test -n "$ACCESS_KEY_ID" -a -n "$ACCESS_KEY_SECRET"; then
	"$path/release/$bin" "$@" --key "$ACCESS_KEY_ID" --secret "$ACCESS_KEY_SECRET"
else
	"$path/release/$bin" "$@"
fi
