#!/usr/bin/env bash
set -e

# make the cwd of this script, the actual directory location of it
# otherwise it could be the cwd of the user, or node_modules/bin
# requires coreutils on mac: brew install coreutils
# https://stackoverflow.com/q/3349105/130638
cd "$(dirname "$(greadlink -f "$0")")"

# determine platform and run the command on it
if test "$(uname -s)" = "Linux"; then
	./release/stout-linux "$@"
elif test "$(uname -s)" = "Darwin"; then
	./release/stout-osx "$@"
else
	./release/stout-windows.exe "$@"
fi
