#!/usr/bin/env bash
set -e
cd "$(dirname "$0")"

rm -Rf ./release
mkdir ./release

data="$(curl -s https://api.github.com/repos/cloudflare/Stout/releases/latest)"
version="$(echo "$data" | jq --raw-output '.tag_name' | sed 's/^v//')"


echo "downloading files from release $version..."

pushd ./release
echo "$data" | jq --raw-output '.assets[] | .browser_download_url' | xargs -t -L 1 wget
chmod +x ./*
popd

ls ./release


echo "updating package version to $version..."

npm version --allow-same-version "$version"

echo "committing and tagging with git..."

git add -u
git commit -m "updated stout to v$version"
git tag "v$version"


echo "publishing new version to npm..."

npm publish


echo "publishing new version to git..."

git push origin master
git push origin --tags


echo "all done"